// @ts-check
import eslint from '@eslint/js';
import eslintPluginPrettierRecommended from 'eslint-plugin-prettier/recommended';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    // src/generated/prisma is regenerated by `prisma generate` (Prisma
    // Client output, PrismaPg driver adapter config) — never hand-edited,
    // so it's never linted. Without this, CI's `prisma generate` step
    // followed by `pnpm run lint` fails on generated files' own formatting
    // (verified against a real generate+lint run), even though project
    // source is clean.
    ignores: [
      'eslint.config.mjs',
      'commitlint.config.js',
      'src/generated/**',
      // Static-rule test fixtures are deliberately "bad" source (undeclared
      // vars, leaked-secret literals, even invalid syntax) read as plain
      // text by the rule specs — never compiled, linted or formatted.
      'src/**/fixtures/**',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  eslintPluginPrettierRecommended,
  {
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.jest,
      },
      sourceType: 'commonjs',
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-floating-promises': 'warn',
      '@typescript-eslint/no-unsafe-argument': 'warn',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      "prettier/prettier": ["error", { endOfLine: "auto" }],
    },
  },
);
